remove clj-time.core from dbutil
clj-time.core is causing the error below, preventing deployment

java.lang.IllegalStateException: second already refers to:
#'clj-time.core/second in namespace: darg.db-util